Revert "Update ci.yml"
This reverts commit 033a2eb4d3cc615d4b098698e1290ac67037399a.

Error: Unexpected input(s) 'projectPath', valid inputs are ['entryPoint', 'args', 'solc-version', 'node-version', 'target', 'sarif', 'slither-args', 'slither-config', 'slither-version', 'ignore-compile']